feat(api): Implement authentication and user management
trakli/trakli-webservice pull request #7
Opened 2024-11-24 20:54 UTC by nfebe

- Added notification service for email notifications
- Implemented registration, login, and forgot password functionality
- Enhanced User model to support username and phone number for login
- Created generic mailer used by the notification service
- Added user seeder to populate test users
- Created events, listeners, and mailer for user registration
- Updated migrations to include phone and username in the users table
- Created a new migration for verification codes
- Added middleware to ensure JSON request body format

Resolves https://github.com/trakli/trakli/issues/6

2024-11-24 22:52 UTC, nfebe reviewed
I have to fix the openapi doc generation or the composer script something weird is going on with one of them.

2024-11-25 11:12 UTC, aanorbel requested changes
🚀

2024-11-25 11:12 UTC, aanorbel commented on app/Events/UserRegisteredEvent.php
> +            new PrivateChannel('channel-name'),
Chang channel name

2024-11-25 11:12 UTC, aanorbel commented on app/Http/Controllers/API/v1/Auth/AuthController.php
> +            'password' => 'required|string|min:8',
add better constraints

2024-11-25 11:12 UTC, aanorbel commented on app/Http/Controllers/API/v1/Auth/AuthController.php
> +        $validatedData['password'] = bcrypt($request->password);
Use `Hash::make($request-> password)`

2024-11-25 11:12 UTC, aanorbel commented on app/Http/Controllers/API/v1/Auth/AuthController.php
> +        $user_data['password'] = bcrypt($request->password);
Use `Hash::make($request-> password)`

2024-11-25 11:12 UTC, aanorbel commented on app/Http/Controllers/API/v1/Auth/ForgotPasswordController.php
> +        return $this->success([], 'Code verified successfully.');
Verification code is retrieved but no action is performed on the code to change the status or the user to change verification status.

2024-11-25 11:12 UTC, aanorbel commented on app/Mail/GenericMail.php
> +            subject: 'Generic Mail',
Keep `i18n` in mind now

2024-11-25 11:12 UTC, aanorbel commented on app/Models/VerificationCode.php
> +    protected $fillable = ['code', 'code', 'purpose', 'expires_at'];
`code` appears multiple times

2024-11-25 11:12 UTC, aanorbel commented on tests/Feature/AuthControllerTest.php
> +    }
Validation with where each rule fails too i neccessary

2024-11-26 22:11 UTC, nfebe commented on app/Http/Controllers/API/v1/Auth/AuthController.php
> +            'password' => 'required|string|min:8',
last_name, username and phone are optional.

2024-11-27 09:46 UTC, aanorbel commented on app/Http/Controllers/API/v1/Auth/AuthController.php
> +            'password' => 'required|string|min:8',
Was thinking of password constraints. We can change that at any time.

2024-11-27 09:47 UTC, aanorbel approved these changes
🐳  🚀

2024-11-27 09:57 UTC, aanorbel approved these changes

2024-11-27 10:01 UTC, merged